### ISSUE TITLE
How different "graph_type" works?

### ISSUE THREAD

**Issue by rowedenny** [dtsbourg/codegraph-fmt#3]
Hi,

Thank you for such interesting work.

I am wondering how "graph_type" affects the generated outputs?
1. For "project_graph", does it means that 1) the tokens vocabulary is shared across all project files, and 2) the corresponding graph is generated individually with the vocabulary, but for "file_graph", the tokens vocabulary is generated individually of each file? Please correct me if I am wrong.

I have read through the code, and what I actually wanna do is
1) have a shared vocabulary across all files within one project
2) generate their individual graph 
It seems that  "slot_graph" should be my option since it has global_voc, that merges all the variable names. Would you please clarify which "graph_type" meet the criterion

Also it raises my second question
2. I also notice that "graph type" could also be "slot_graph" or "test", so what is the difference between the previous two?

Thank you for your time.

**Comment by dtsbourg** [comment]
Hi @rowedenny,

Sorry for the delay in response. 

- `project_graph` treats the entire project as the code to be processed, so generates one large graph from the entire source code. This was mostly used for small test projects of course, as it grows quite quickly.
- `file_graph` creates a single graph per file, and saves each to a separate file as well.
- `slot_graph` pre-processes the data to hide a certain type of token, e.g. variable names. It replaces it by a `[MASK]` token and saves the replaced token to file.
- `test` just runs the processing steps on the entire set of files (no filter for test/train), usually if you already know that a given folder only contains the set of files you are interested in.

Generally speaking, the global vocab can be provide anywhere with no restriction on the `graph_type`. For your application, I would probably try `file_graph` first, it seems to meet the criteria of what you are looking for.

Hope this helps!

**Comment by rowedenny** [comment]
Hi @dtsbourg 
Thanks for your response in detail.

Here is a more concrete example, say we have 100 code files across the project, and the number of nodes including AST nodes predefined and variable names is 1,000, that's to say the size of the vocabulary is 1000.
Then what I expect is:
1. For each code file, we could generate one 1000 x 1000 adjacent matrix as a graph
2. In total, we have 100 adjacent matrices.
3. The same variable name is mapped with the same id in different graphs.

I summarize different graph types on this context, please correct me if I am wrong.
* `project_graph` will generate **only one** graph, so it does not fit. 
* `file_graph` will generate 100 graphs, but the size of the adjacent matrix could vary, plus the same variable name may be mapped with different id in different graphs, so it does not fit either.
* `slot_graph` indeed provides 100 adjacent matrices as independent graphs and the adjacent matrix corresponding to each graph has the **same** size. The only minor difference is the variable names are replaced.

If my understanding is correct, then only the gap is to "maintain the variable names as its original tokens", then would you mind specify how to make it.


Thanks ahead.

**Comment by dtsbourg** [comment]
Hi, 

Unfortunately I don't think what you are searching for is implemented currently. We use the AST as the graph structure, but do not provide a co-occurence matrix based on the vocabulary. This shouldn't be too hard to build though. For example, instead of adding a node based on the token count, you could create a 1000 node graph based on the vocabulary you have, then instead of adding nodes here https://github.com/dtsbourg/codegraph-fmt/blob/master/src/ast_processor.py#L184 you would create an edge between the corresponding nodes. This should emulate the behavior you are looking for.

**Comment by rowedenny** [comment]
I see.

May I say that based on the current implementation, the nodes in a graph are predefined in the 
AST_SYMBOL_DICT of https://github.com/dtsbourg/codegraph-fmt/blob/master/src/ast_utils.py.

And based on your suggestion, I need to generate extra co-occurrence matrix on the vocabulary.
More concretely, the for a AST, the current graph only contains non-leaf node, and ignore the leaf node, please correct me if I am wrong.

**Comment by dtsbourg** [comment]
The link you shared refers to the node types. These can be used as features or, as we do here, as nodes in the AST. This includes leaf nodes (we explicitly extract those from the AST node fields)

**Comment by rowedenny** [comment]
I see.
Thanks for your considerate replies.
